### ISSUE TITLE
Zobrazování poznámek u itemů / názvu kategorií / názvu itemů

### ISSUE THREAD

**Issue by Killerbunnyn** [Dimitros617/VRS2020#39]
Když je u itemu vložená delší poznámka, není text vidět celý. Asi by stačilo jen přidat nějaké zalamování, aby byla poznámka ("note") na víc řádků...

U Názvu itemu a kategorie ideálně umožnosti mít napsaný text v PC do celé řádky toho boxu, případně taky zalamovat..

**Comment by LivvW** [comment]
Doplnění issue: Přizpůsobit textové pole na popis kategorie podle délky popisu. Když se přímo kategorie rozklikne, tak je tam scrollbar, ale je pak problém v souhrnu kategorií na straně /categories, člověk nevidí celý popis.
