### ISSUE TITLE
Na úvodní straně (localhost welcome) doplnit tlačítka Přihlášení, Registrace, Hlavní strana - mobilní verze

### ISSUE THREAD

**Issue by LivvW** [Dimitros617/VRS2020#54]
Na mobilní verzi nejsou vidět výše zmíněná tlačítka. Na verzi pro iPad ale už ano. Sice na obrázku je odkaz vedoucí na login a je to propojené, ale nějakou jednotnost by to chtělo.
Možná ještě doplnění, co tam dát i menší logo? (jen to "V" s čárkama) 
![Screenshot_92](https://user-images.githubusercontent.com/72982289/104813868-221b5300-580c-11eb-842d-7e777c658c6d.png)

**Comment by Kacenka21** [comment]
vyřešeno - přihlášení a registrace - k hlavní stránka se neumim dostat
