### ISSUE TITLE
Nadpis mezi rozbalenými výpůjčkami na all-loans

### ISSUE THREAD

**Issue by LivvW** [Dimitros617/VRS2020#57]
Mít, když rozbalíme záložku Aktivní výpůjčky, pod ní ještě nadpis Aktivní výpůjčky či ne? V základu přehlednosti, pokud zůstanou rozbaleny všechny záložky, tak by si jednotlivé záznamy zasloužily možná oddělení nadpisem.
Obrázek pro lepší představu
![Screenshot_97](https://user-images.githubusercontent.com/72982289/104818242-abd81a00-5826-11eb-9bc9-e6c9a04fd742.png)

**Comment by Killerbunnyn** [comment]
jsem pro oddělení nadpisem nebo nějaký štítek u těch výpůjček, aby bylo jaké jaké jsou aktivní a jaké už ne. Ale myslím, že předěl nadpisem bude nejjednodušší a nejpřehlednější cesta
