### ISSUE TITLE
Na dashboardu se tlačítka nehážou pod sebe na mobilní verzi

### ISSUE THREAD

**Issue by LivvW** [Dimitros617/VRS2020#60]
![Screenshot_99](https://user-images.githubusercontent.com/72982289/104903066-dbe70080-597f-11eb-89df-c5c5276490e9.png)
Mají být na mobilu pod sebou.

Zároveň je na mobilní verzi asi až moc velký padding podle mého názoru

**Comment by LivvW** [comment]
Ok, nejsou ani na stránce půjčení itemu, ale na seznamu uživatelů ano, tam jsou správně seřazeny pod sebe, brát tedy inspiraci tam.

**Comment by Kacenka21** [comment]
snad vyřešeno
