### ISSUE TITLE
Problém s přístupem na category, categories

### ISSUE THREAD

**Issue by LivvW** [Dimitros617/VRS2020#65]
V routě je nastaveno, že má přístup pouze ten s permition possibility_renting, ale potřebujeme to na tři - Auth::permition()->return_verification == 1 || Auth::permition()->possibility_renting == 1 || Auth::permition()->edit_item == 1

Stačí pouhým OR?
Ověřit, kde všude to ještě musí být!

**Comment by LivvW** [comment]
Ok, vyřešit zapsáním podmínky do daného controlleru a vynechat to ověření v routě je jedna z možností? 
S tím upravit visibility záložky Nová výpůjčka pro uživatele s permition edit_item nebo return_verification, který nebude mít zároveň possibility_renting
Pro jiný do else hodit return 403, ale je problém, jak jsou ty views ve vendoru, potřebuju je teda publikovat.

Ve výsledku by bylo snazší fakt zjistit, zda se dá do routy napsat syntaxe ORu..

**Comment by Dimitros617** [comment]
Jsem na cestě
Dne st 20. 1. 2021 22:00 uživatel LivvW <notifications@github.com> napsal:
