### ISSUE TITLE
Špatný databázový typ či záměr?

### ISSUE THREAD

**Issue by tjakes** [Dimitros617/VRS2020#75]
V DB je rent_from a rent_to typu varchar(255) a ne jako datetime či timestamp? Je v tom záměr? Pokud je využíván jako text není délka 255 zbytečná (jaká je maximální délka)?

**Comment by LivvW** [comment]
Původně se mělo jednat o DATE i podle původního návrhu, pak tam ale zůstal varchar kvůli tomu, že se nevědělo, jak se bude chovat datepicker na výběru data výpůjčky - respektive ten to vybíral v opačném formátu než je date, tedy např. 15-02-2021, zatímco date měl nejdřív rok. Takže napůl záměr, napůl chybka. :-) Nyní je to však změněno, upraveno a vše by mělo fungovat a ve všech tabulkách využívající toto datum (loans, loans_histories) je již tento sloupec upraven na DATE.
